### PR TITLE
Pass resolver overrides to the factory method of RegisterFactory

### PR DESCRIPTION
**Pull request by hypercodeplace**
Description of the issue is here: https://github.com/unitycontainer/container/issues/147

### CODE REVIEW

**Comment by ENikS** [comment]
There is a lot easier way to pass data to factory delegate other than to change 10 years old interface. All you have to do is to create a 'closure' and pass anything you want through it:
```C#
 this._someObject = Data;
...
Container.RegisterFactory<IService>(c => new Service(  this._someObject ) );
```

If you pass resolver overrides into factory method, you are shifting resoponsibility to process them to the consumer (the delegate author), who might not have a clue how to do it. 

I do not think it is an improvement. Will have to decline.
Next time, before jumping the gun, perhaps you could open an issue and we could talk about it?

**Comment by hypercodeplace** [comment]
>There is a lot easier way to pass data to factory delegate other than to change 10 years old interface. All you have to do is to create a 'closure' and pass anything you want through it:

As I mentioned [here](https://github.com/unitycontainer/container/issues/147#issue-422552996) there are scenarios it's needed to wrap all `.Resolve` by a factory, but pass all `resolver overrides` in the same way as `name` or `type`. A real example is [dynamically built proxy](https://github.com/servicetitan/lazy-proxy-unity/blob/master/LazyProxy.Unity/UnityExtensions.cs#L154). In this cases "closure" is not enough because it's needed to pass `resolver overrides` to the factory like `name` or `type` that changed from resolve to resolve.

In the example above it's used dynamically built proxy to wrap resolves in lazy way. Suggested pull request allows to do it like this:

```C#
return container
    .RegisterType(typeFrom, typeTo, registrationName, typeLifetimeManager, injectionMembers)
    .RegisterFactory(typeFrom, name,
        (c, t, n, o) => LazyProxyBuilder.CreateInstance(t, () => c.Resolve(t, registrationName, o)),
        factoryLifetimeManager);
```

Could you suggest how to solve this problem in the way with "closures" suggested by you?

>If you pass resolver overrides into factory method, you are shifting resoponsibility to process them to the consumer (the delegate author), who might not have a clue how to do it.

If the author don't have a clue how to do it, he can still use overloads without resolver overrides.

**Comment by ENikS** [comment]
Look at these [two samples](https://github.com/unitycontainer/examples/tree/master/src/Extending%20Unity). These show a way to register ‘grownup’ factories with full access to resolvers and etc.
Internal Unity factories for `Func` an `Lazy` are implemented using this way.

The only limitation, you might have to create an extension to register it.

**Comment by hypercodeplace** [comment]
>Look at these [two samples]

Thank you, but suggested approach doesn't allow to keep the lifetime for dynamically built proxy same as for the inner registration. Look at the following code that illustrates it.

`RegisterLazy` method body from [here](https://github.com/servicetitan/lazy-proxy-unity/blob/master/LazyProxy.Unity/UnityExtensions.cs#L154) changed according to your proposed approach:
```C#
return container.AddExtension(
    new LazyProxyUnityExtension(typeFrom, typeTo, name, getLifetimeManager(), injectionMembers)
);
```

```C#
public class LazyProxyUnityExtension: UnityContainerExtension
{
    private readonly Type _typeFrom;
    private readonly Type _typeTo;
    private readonly string _name;
    private readonly ITypeLifetimeManager _lifetimeManager;
    private readonly InjectionMember[] _injectionMembers;

    public LazyProxyUnityExtension(
        Type typeFrom,
        Type typeTo,
        string name,
        ITypeLifetimeManager lifetimeManager,
        params InjectionMember[] injectionMembers)
    {
        _typeFrom = typeFrom;
        _typeTo = typeTo;
        _name = name;
        _lifetimeManager = lifetimeManager;
        _injectionMembers = injectionMembers;
    }

    protected override void Initialize()
    {
        var registrationName = Guid.NewGuid().ToString();

        Context.Container.RegisterType(_typeFrom, _typeTo, registrationName, _lifetimeManager, _injectionMembers);

        Context.Policies.Set(_typeFrom, _name, typeof(ResolveDelegateFactory),
            (ResolveDelegateFactory) ((ref BuilderContext _) =>
            {
                return (ref BuilderContext c) =>
                {
                    var type = c.Type;
                    var overrides = c.Overrides;

                    // It executes every time and creates new instance even in case
                    // passed `lifetimeManager` is `ContainerControlledLifetimeManager`
                    // There is no chance to keep the same lifetime that was used to registration.
                    return LazyProxyBuilder.CreateInstance(type,
                        () => Context.Container.Resolve(type, registrationName, overrides)
                    );
                };
            })
        );
    }
}
```

To be clear, this test fails:
```C#
[Fact]
public void ServicesMustBeResolvedByNameWithCorrectLifetime()
{
    var container = new UnityContainer()
        .RegisterLazy<IService, Service>(() => new ContainerControlledLifetimeManager());

    Assert.Same(
        container.Resolve<IService>(),
        container.Resolve<IService>()
    );
}
```

Could you suggest anything that can help?

**Comment by hypercodeplace** [comment]
**Update:** have solved this by adding line of the second registration: `Context.Container.RegisterType(_typeFrom, _typeTo, _name, _lifetimeManager());`

**Comment by hypercodeplace** [comment]
But looks like registered `Policies` are not presented at child containers? Is there a way to keep it?

**Comment by ENikS** [comment]
But it does. Look like 'Lazy<>' is implemented.

**Comment by hypercodeplace** [comment]
Yes, you are right, it works properly. Approach with `UnityContainerExtension` solves mentioned task. But for each `.RegisterLazy` new instance of `LazyProxyUnityExtension` is required. 1000 registrations -> 1000 extensions in the container. Is it ok to the performance?

Just in case I will provide the latest correctly working version of the `Initialize` method of `LazyProxyUnityExtension`:

```C#
protected override void Initialize()
{
    var registrationName = Guid.NewGuid().ToString();

    Context.Container.RegisterType(_typeFrom, _typeTo, _name, _lifetimeManager());
    Context.Container.RegisterType(_typeFrom, _typeTo, registrationName, _lifetimeManager(), _injectionMembers);

    Context.Policies.Set(_typeFrom, _name, typeof(ResolveDelegateFactory),
        (ResolveDelegateFactory) ((ref BuilderContext _) =>
            (ref BuilderContext c) =>
            {
                var container = c.Container;
                var type = c.RegistrationType;
                var overrides = c.Overrides;

                return LazyProxyBuilder.CreateInstance(type,
                    () => container.Resolve(type, registrationName, overrides)
                );
            })
    );
}
```

**Comment by ENikS** [comment]
There shouldn’t be too many factories, usually one per type is sufficient.

Perhaps you still not doing it correctly?

**Comment by hypercodeplace** [comment]
> There shouldn’t be too many factories, usually one per type is sufficient. Perhaps you still not doing it correctly?

I have one factory per (type,name). There are so many factories (extensions) because lazy proxy is built for each registration. 

That is why I supposed to pass `resolver overrides` to the factory of `.RegisterFactory` because it is the same as `type` or `name`. But are you still against the proposed approach?

If so, I will appreciate if you say what definitely wrong with the presented code and how to avoid adding an extension per registration?

**Comment by ENikS** [comment]
Alexey,

The factory I suggested has BuilderContext passed in during resolution. It has Resolver Overrides array as a member.

Is in not what you wanted?

**Comment by hypercodeplace** [comment]
> Alexey, The factory I suggested has BuilderContext passed in during resolution. It has Resolver Overrides array as a member. Is it not what you wanted?

Yes, it solves the problem, but my last message is not about it. It's about performance issue. We tested and compared the approach suggested in this PR (`.RegisterFactory` with resolver overrides) and your approach (adding a policy for registration). The result is your way is worse on 20...40% for the first resolve. The second and following resolves are equal for both ways.

So, for our company your way is acceptable but a little bit worse for performance.

Also we still believe that `.RegisterFactory` must contain resolver overrides as well as name and type because logically it is absolutely the same: arguments passed to create instances. Factory method must contains all arguments, but for now it's only type and name. It's strange. And looks like your way is only workaround for obvious defect of the current implementation of `.RegisterFactory`. 

You said "There is a lot easier way to pass data to factory delegate other than to change 10 years old interface." we suppose it's better to fix the interface after 10 year then never, especially if you changed it yourself recently https://github.com/unitycontainer/abstractions/issues/89. 

I hoped that completely done pull requests and described issue helps to accept it, but unfortunately you rejected it for reasons not entirely clear. Sad but true.

**Pull request closed without merging**
